services:
  http-server:
    container_name: http-server
    build:
      context: .
      dockerfile: docker/http/Dockerfile.server
    networks:
      - testnet
    ports:
      - "3000:3000"

  http-client:
    container_name: http-client
    build:
      context: .
      dockerfile: docker/http/Dockerfile.client
    networks:
      - testnet
    depends_on:
      - http-server
    environment:
      TARGET: http-server:3000
    volumes:
      - ./data:/app/data

  websocket-server:
    container_name: websocket-server
    build:
      context: .
      dockerfile: docker/websocket/Dockerfile.server
    networks:
      - testnet
    ports:
      - "3000:3000"

  websocket-client:
    container_name: websocket-client
    build:
      context: .
      dockerfile: docker/websocket/Dockerfile.client
    networks:
      - testnet
    depends_on:
      - websocket-server
    environment:
      TARGET: websocket-server:3000
    volumes:
      - ./data:/app/data

  grpc-server:
    container_name: grpc-server
    build:
      context: .
      dockerfile: docker/grpc/Dockerfile.server
    networks:
      - testnet
    ports:
      - "50051:50051"

  grpc-client:
    container_name: grpc-client
    build:
      context: .
      dockerfile: docker/grpc/Dockerfile.client
    networks:
      - testnet
    depends_on:
      - grpc-server
    environment:
      TARGET: grpc-server:50051
      PAYLOAD_KB: 1
      TOTAL_REQUESTS: 1
      CONCURRENCY: 1
      OUTPUT_PATH: /app/data/raw/test/request-results.json
    volumes:
      - ./data:/app/data

networks:
  testnet:
